---
title: "Data Flip"
author: "Connor Flynn"
date: "9/27/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readxl)
library(viridis)
library(plotly)
library(janitor)
library(naniar)
library(ggpubr)
library(GGally)
library(corrplot)

options(scipen = 99)
```


The purpose of this Rmd is to explore data collected by Matau Faiai for her PhD Dissertation (Yale School of Epidemiology)


Read in Data

```{r, include=FALSE}
rankings_data <- read_excel(here("data/food_sorting_data.xlsx"))
```



```{r, include=FALSE}
rankings_data
```



```{r, include=FALSE}
rankings_data_tidy <- rankings_data %>%
  pivot_longer(
    cols = starts_with(c("banana_", "apple_", "orange_", "papaya_", "avocado_", "eggplant_", 
                         "laupele_", "rice_", "bread_", "cereal_", "breadfruit_", "eggs_", 
                         "spam", "frychix_", "pancake_", "icecream_", "pizza_", "hamburger_", 
                         "nuggets_", "fries_", "juices_", "soda_", "water_", "shoyuchix_", 
                         "mackerel_", "bakedchix_", "chips_", "cookies_")),
    names_to = "food_characteristic",
    values_to = "value"
  ) %>%
  separate(food_characteristic, into = c("food", "characteristic"), sep = "_", remove = FALSE) %>%
  select(-food_characteristic)
```

```{r, include=FALSE}
rankings_data_tidy
```



Flip it!

```{r, include=FALSE}
rankings_data_tidy_flipped <- rankings_data_tidy %>%
  mutate(value = max(value, na.rm = TRUE) + 1 - value)
```



```{r, include=FALSE}
rankings_data_tidy_flipped_mean <- rankings_data_tidy_flipped %>% 
  group_by(food, characteristic) %>% 
  summarise(mean = mean(value, na.rm = TRUE))
```

```{r, include=FALSE}
rankings_data_tidy_flipped_mean_wider <- rankings_data_tidy_flipped_mean %>% 
  pivot_wider(names_from = characteristic, 
              values_from = mean)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
ggplot(data = rankings_data_tidy_flipped_mean_wider, aes(x = cost,
                                                 y = social,
                                                 label = food)) +
  geom_point() +
  geom_smooth(method = "lm", color = "blue") + 
  stat_cor() +# Add a linear regression line
  theme_minimal() +
  geom_text(hjust=0, vjust=0) +
  labs(title = "Average Social Rankings vs Average Cost Ranking",
       x = "Cost (least expensive to most expensive)",
       y = "Social Status (least popular to most popular)")
```








```{r, include=FALSE}
rankings_data_tidy_flipped <- rankings_data_tidy_flipped %>% 
  group_by(food) %>% 
  mutate(median = median(value, na.rm = TRUE))
```



```{r, echo=FALSE}
ggplot(data = rankings_data_tidy_flipped, aes(y = reorder(food, median), x = value, fill = characteristic)) +
  geom_boxplot() +
  theme_minimal() +
  facet_wrap(~characteristic)
```

```{r, include=FALSE}
rankings_data_tidy_flipped_cost <- rankings_data_tidy_flipped %>% 
  filter(characteristic == "cost")

ggplot(data = rankings_data_tidy_flipped_cost, aes(y = reorder(food, median), x = value, fill = characteristic)) +
  geom_boxplot() +
  theme_minimal()
```







Scatter Plots and Stats

```{r, include=FALSE}
rankings_data_wide <- rankings_data_tidy_flipped %>%
  pivot_wider(
    names_from = characteristic,
    values_from = value
  )
```


```{r, echo=FALSE}
# Create the scatter plot with ggplot
ggplot(rankings_data_wide, aes(x = cost, y = social)) +
  geom_point() +  # Add points
  geom_smooth(method = "lm", color = "blue") + 
  stat_cor() +# Add a linear regression line
  theme_minimal()   +# Apply a minimal theme
  ylim(0, 35)


```


```{r, echo = FALSE}
plot <- ggplot(data = rankings_data_wide, 
       aes(x = cost,
           y = social, 
           size = healthy,
           color = food)) +
  geom_point(alpha = 0.5) +
  theme_minimal() +
  scale_color_viridis(discrete=TRUE)

ggplotly(plot)
```




Correlation Matrix



```{r, include=FALSE}
rankings_data_wide_no_na <- drop_na(rankings_data_wide)

rankings_data_wide_corr <- rankings_data_wide_no_na %>% 
  clean_names() %>% 
  ungroup() %>% 
  select(-participant_id, -median, -food) 
```

```{r, include=FALSE}
# Create a correlation matrix


corr <- cor(rankings_data_wide_corr)


```



```{r, echo = FALSE}

# Plot the correlation matrix with text labels
corrplot(corr, method = "circle", type = "lower", tl.col = "black", diag = FALSE, addCoef.col ='black')
```