---
title: "Rankings"
author: "Connor Flynn"
date: "8/14/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(readxl)
library(viridis)
library(plotly)
library(janitor)
library(naniar)
```

Read in Data

```{r}
rankings_data <- read_excel(here("data/food_sorting_data.xlsx"))
```



```{r}
rankings_data
```



```{r}
rankings_data_tidy <- rankings_data %>%
  pivot_longer(
    cols = starts_with(c("banana_", "apple_", "orange_", "papaya_", "avocado_", "eggplant_", 
                         "laupele_", "rice_", "bread_", "cereal_", "breadfruit_", "eggs_", 
                         "spam", "frychix_", "pancake_", "icecream_", "pizza_", "hamburger_", 
                         "nuggets_", "fries_", "juices_", "soda_", "water_", "shoyuchix_", 
                         "mackerel_", "bakedchix_", "chips_", "cookies_")),
    names_to = "food_characteristic",
    values_to = "value"
  ) %>%
  separate(food_characteristic, into = c("food", "characteristic"), sep = "_", remove = FALSE) %>%
  select(-food_characteristic)
```

```{r}
rankings_data_tidy
```




```{r}
rankings_data_wide <- rankings_data_tidy %>%
  pivot_wider(
    names_from = characteristic,
    values_from = value
  )
```


```{r}
plot <- ggplot(data = rankings_data_wide, 
       aes(x = cost,
           y = social, 
           size = healthy,
           color = food)) +
  geom_point(alpha = 0.5) +
  theme_minimal() +
  scale_color_viridis(discrete=TRUE)

ggplotly(plot)
```

```{r}
rankings_data_tidy <- rankings_data_tidy %>% 
  group_by(food) %>% 
  mutate(median = median(value, na.rm = TRUE))
```



```{r}
ggplot(data = rankings_data_tidy, aes(y = reorder(food, median), x = value, fill = characteristic)) +
  geom_boxplot() +
  theme_minimal() +
  facet_wrap(~characteristic)
```
upumoni_graph

```{r}
mean_rankings <- rankings_data_wide %>% 
  group_by(food) %>% 
  summarize(mean_cost = mean(cost, na.rm = TRUE), 
            mean_healthy = mean(healthy, na.rm = TRUE),
            mean_social = mean(social, na.rm = TRUE))
```

```{r}
mean_rankings_longer <- mean_rankings %>% 
  pivot_longer(cols = mean_cost:mean_social,
               names_to = "characteristic_mean",
               values_to = "mean_value")
```


```{r}
ggplot(mean_rankings_longer, aes(x = mean_value, y = reorder(food, mean_value))) +
  geom_bar(stat = "identity") +
  facet_wrap(~characteristic_mean) +
  theme_minimal()
```

Cluster Analysis

```{r}
rankings_data_wide <- rankings_data_wide %>% 
  clean_names()
```



```{r}
null_participants <- c("5", "29", "31", "32")

rankings_data_tidy <- rankings_data_tidy %>% 
  clean_names()

rankings_data_tidy_no_na <- rankings_data_tidy %>% 
  filter(! participant_id %in% null_participants)

unique(rankings_data_tidy_no_na$participant_id)

rankings_data_tidy_no_na <- rankings_data_tidy_no_na %>% 
  select(-median)
```

```{r}
rankings_data_tidy_no_na <- rankings_data_tidy_no_na %>%
  unite(participant_characteristic, characteristic, participant_id, sep = "_")

```

```{r}
rankings_data_tidy_no_na <- rankings_data_tidy_no_na %>% 
  pivot_wider(names_from = participant_characteristic,
              values_from = value)
```

```{r}
sum(is.na(rankings_data_tidy_no_na))
```

```{r}
gg_miss_var(rankings_data_tidy_no_na)
```
```{r}

rankings_data_tidy_no_na[is.nan(rankings_data_tidy_no_na)] <- NA


rankings_data_tidy_no_na <- rankings_data_tidy_no_na %>%
  mutate(across(everything(), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .)))
```

```{r}
sum(is.na(rankings_data_tidy_no_na))
```


Correlation Matrix

```{r}
rankings_data_wide_no_na <- drop_na(rankings_data_wide)

rankings_data_wide_corr <- rankings_data_wide_no_na %>% 
  select(-participant_id, -food)
```

```{r}
# Create a correlation matrix


corr <- cor(rankings_data_wide_corr)

corr_data_frame <- as.data.frame(corr)
```


```{r}
library(GGally)
 
# Nice visualization of correlations
ggcorr(corr_data_frame, method = c("everything", "pearson")) 
```



One graph at a time for cost, healthy, social

Include cost and social status in box plot looking at all of the food items

